# Profile section
profile:
  first_name: Gilvan
  last_name: Almeida
  picture: static/img/perfil.jpg # Local picture
  contact:
    address_one: Cork, Irlanda
    address_two:
    phone: +353 83 206 9111
  email: gilvan.praxedes@outlook.com
  description: >
    Profissional bilíngue (Português e Inglês) com graduação em Ciência da Computação e mais de 8 anos de experiência em desenvolvimento de software, full-stack, DevOps, administração de bancos de dados SQL e suporte a clientes em empresas multinacionais como Wood Group, Johnson & Johnson, ChampionX, Nalco, Itaú, PayPal, LATAM, Certisign e ONS.
    Atualmente, estou cursando o MSc em Software Design com Cloud Native Computing na Technological University of the Shannon (TUS), Irlanda, com foco em arquiteturas cloud-native modernas, práticas de DevOps e sistemas de software escaláveis.
    Possuo habilidades em C#, Python, frameworks front-end (Angular, Vue, React), TypeScript, SQL, além de familiaridade com plataformas de nuvem como AWS e Azure. Também tenho experiência com MongoDB, SQL Server, MySQL, testes unitários e de API, arquitetura de software e projetos de engenharia em equipe.
    Sou apaixonado por aprendizado contínuo, gosto de enfrentar desafios, melhorar sistemas e entregar soluções que aprimorem a experiência do usuário e o desempenho das aplicações.
# Social section
social:
  github: https://github.com/iamgilvan
  linkedin: https://www.linkedin.com/in/gilvan-almeida/

tip: Click no link a esquerda para trocar o idioma.
# Experience section
experience:
  item0:
    position: Desenvolvedor de Software
    company: Screendragon
    from: Março 2025
    to: Atual
    description:
      item0: 
        text: Desenvolvi APIs e aplicações web com foco em escalabilidade e responsividade.
      item1: 
        text: Colaborei em revisões de design e contribui para requisitos de produto e arquitetura.
      item2: 
        text: Automatizei processos de release e deployment para aumentar a eficiência.
      item3: 
        text: Modelei bancos de dados e defini estruturas de dados.
      item4: 
        text: Conquista - Entreguei soluções que atenderam às necessidades técnicas e dos clientes.
    link: https://www.screendragon.com/
  item1:
    position: Desenvolvedor Full Stack/Desenvolvedor de Banco de Dados SQL
    company: Version 1
    from: Março 2022
    to: Março 2025
    description:
      item0: 
        text: Desenvolvi componentes de front-end e back-end usando .NET Core e Vue.js.
      item1: 
        text: Modelei e otimizei bancos de dados SQL Server e pipelines de ETL.
      item2: 
        text: Construí APIs RESTful e melhorei a performance do sistema (60% de redução no tempo de carregamento).
      item3: 
        text: Automatizei processos de build e deployment com TeamCity e Octopus Deploy.
      item4: 
        text: Conquista - Melhorei a performance e a manutenção de sistemas corporativos para clientes como Johnson & Johnson e Wood Group.
    link: https://www.version1.com/
  item2:
    position: Desenvolvedor Full Stack/Desenvolvedor DevOps/Administrador de Banco de Dados SQL
    company: Radix Engenharia e Software
    from: Maio 2019
    to: Fevereiro 2022
    description:
      item0: 
        text: Desenvolvi aplicações full-stack com C# e Angular.
      item1: 
        text: Modelei e gerenciei bancos de dados SQL Server e soluções Azure SQL.
      item2: 
        text: Configurei pipelines de CI/CD no Azure DevOps e automatizei deploys.
      item3: 
        text: Realizei tuning de sistemas, testes e documentação.
      item4: 
        text: Conquista - Entreguei aplicações críticas para ChampionX e ONS, aumentando a eficiência operacional.
    link: http://www.radixeng.com.br/
  item3:
    position: Desenvolvedor de Software 
    company: BigData Corp.
    from: Setembro 2017
    to: Abril 2019
    description:
      item0: 
        text: Desenvolvi serviços em nuvem e APIs para clientes como Itaú, PayPal e LATAM.
      item1: 
        text: Construí sistemas distribuídos para dados públicos, notícias e inteligência de mercado.
      item2: 
        text: Mantive bancos de dados SQL Server e NoSQL, pipelines de ETL e ferramentas de monitoramento.
      item3: 
        text: Conquista - Criei soluções escaláveis que reduziram custos dos clientes em 50% e suportaram contratos multimilionários.
    link: https://bigdatacorp.com.br/
  item4:
    position: Bolsista de desenvolvimento web
    company: Fiocruz
    from: Novembro 2014
    to: Setembro 2017
    description:
      item0: 
        text: Apoiei no desenvolvimento de sistemas internos e scripts de automação.
      item1: 
        text: Contribuí na otimização de bancos de dados e sistemas de gestão de registros.
      item2: 
        text: Conquista - Apoiei na digitalização completa do inventário de ativos.
    link: https://portal.fiocruz.br/


# Education section
education:
  item0:
    institution: Technological University of the Shannon (TUS) | Irlanda
    program: Mestrado em Software Design com Cloud Native Computing
    description: >
      Principais módulos:
        Microsserviços e aplicações conteinerizadas (Docker, Kubernetes)
      | Integração Contínua e Entrega Contínua (CI/CD) e automação DevOps
      | Programação Orientada a Objetos e Scripting Aplicado
      | Arquitetura de software e projetos de engenharia em equipe
      | Métodos de pesquisa, prática profissional e dissertação/estágio na indústria
    from: Setembro 2025
    to: Setembro 2026
  item1:
    institution: Instituto Militar de Engenharia - IME/RJ
    program:  Mestre em Sistemas e Computação
    description: >
      Módulos: Desenvolvimento de Plataformas Computacionais para Apoiar a Tomada de Decisão, Aprendizado de Máquina, Inteligência Artificial Aplicada, Desenvolvimento de Sistemas Computacionais e Design e Análise de Algoritmos.
      Trabalho de Tese: Detecção de discurso de ódio em imagens publicadas como comentários em mídias sociais.
    from: Fevereiro 2020
    to: Julho de 2022 (Não Finalizado)
  item2:
    institution: Centro Universitário Carioca - Unicarioca/RJ
    program: >
      Bacharelado em Ciência da Computação
    description: Computação/Informação, tecnologia, desenvolvimento, administração e gerenciamento.
    from: Julho 2013
    to: Dezembro 2018

# Skills section
tools:
  # Consider that the following are icons:
  #   https://icons8.com/icons
  item1:
    img: c-sharp-logo-2
    title: C#
  item2:
    img: python
    title: Python
  item3:
    img: mysql-logo
    title: Mysql
  item4:
    img: angularjs
    title: Angular
  item5:
    img: docker
    title: Docker
  item6:
    img: linux
    title: Linux
  item8:
    img: django
    title: Django
  item9:
    img: microsoft-sql-server
    title: Sql Server
  item10:
   img: vue-js
   title: VueJs
  item11:
    img: amazon-web-services
    title: AWS Services
  item12:
    img: typescript
    title: typescript
  item13:
   img: sql
   title: Sql
  item14:
    img: mongodb
    title: MongoDB
  item15:
    img: github
    title: Git
  item16:
    img: javascript
    title: javascript
  item19:
    img: bash
    title: bash
  item20:
    img: bootstrap
    title: bootstrap

menu:
  item1:
    title: Sobre
  item2:
    title: Habilidade
    extraInfo1: Linguagens de Programação e ferramentas
    extraInfo2: Habilidades extras / Conhecimentos
    extraInfo3: Passe o mause sobre os ícones
  item3:
    title: Experiência
  item4:
    title: Educação
  item5:
    title: Eventos
    extraInfo1: Alguns dos recentes eventos ...
  item6:
    title: Projetos Pessoais
    extraInfo1: Esta seção contém alguns projetos que eu desenvolvi e exercitei.


extra_skills:
  - Nuvem - Microsoft Azure (App Services, Azure Functions, Service Bus, ADF), AWS (EC2, S3, SQS)
  - DevOps - CI/CD, Azure DevOps, GitHub, GitLab, Docker, TeamCity, Octopus Deploy
  - Arquitetura - Microsserviços, Event-driven, RESTful APIs, Sistemas Cloud-Native
  - Testes - Testes unitários, Testes de integração, TDD
  - Metodologias - Scrum, Agile, Clean Code, princípios SOLID

# Talks and workshops section
workshops:
  item0:
    event: >
      AWS Summit London
    workshop: O AWS Summit London é o nosso maior evento gratuito de tecnologia em nuvem no Reino Unido, Abril de 2025.
    material:
    link: https://aws.amazon.com/events/summits/london/
  item1:
    event: >
      Microsoft Azure Virtual Training Day: Data Fundamentals
    workshop: Microsoft Online Training Day, Setembro 2024.
    material:
    link: https://events.microsoft.com/
  item2:
    event: >
      GitHub and Azure: Better Together!
    workshop: Microsoft Online Training Day, Setembro 2024.
    material:
    link: https://events.microsoft.com/

# Projects section
projects:
  item11:
    título: Padrões de Projeto em csharp
    subtítulo: " "
    descrição: Padrões de Projeto em csharp - Curso
    github: https://github.com/iamgilvan/design-patterns-in-csharp
    tags: [Csharp]
  item10:
    título: Programação Orientada a Objetos com Python
    subtítulo: " "
    descrição: Programação Orientada a Objetos com Python - Curso
    github: https://github.com/iamgilvan/oop_python
    tags: [Python]
  item0:
    title: Blind-75-Must-Do-Leetcode
    subtitle: Perguntas de entrevista de programação
    description: Uma lista de problemas do Blind 75 Leetcode
    github: https://github.com/iamgilvan/Blind-75-Must-Do-Leetcode
    tags: [Python]
  item1:
    title: CtCI-6th-Edition
    subtitle: Perguntas de entrevista de programação
    description: 189 perguntas de entrevista de programação, desde o básico até os problemas de algoritmo mais complicados.
    github: https://github.com/iamgilvan/CtCI-6th-Edition
    tags: [Python]
  item2:
    title: THOW-WEB
    subtitle: Apoio Multicritério à Decisão
    description: Aplicação Web que utiliza um algoritmo híbrido de apoio à decisão para processos decisórios com alternativas discretas. http://www.thor-web.com/
    github: https://github.com/iamgilvan/thor-web
    tags: [Flask, Python, Bootstrap, Heroku, MongoDB]
  item3:
    title: flask currículo template
    subtitle: Currículo desenvolvido com Flask
    description: Uma aplicação de simples configuração desenvolvido com Flask.
    github: https://github.com/iamgilvan/flask-resume
    tags: [Flask, Python, Bootstrap]
  item4:
    title: TDD Python Exemplo
    subtitle: Teste unitário
    description: Exemplo de teste unitário com python.
    github: https://github.com/iamgilvan/tdd-python-example
    tags: [Python, Unit Test, PyTest]
  item5:
    title: Conversão de moedas
    subtitle:  Conversão entre diferentes moedas
    description: O principal objetivo dessa api desenvolvida em python é fazer conversão entre diferentes moedas com a cotação mais recente.
    github: https://github.com/iamgilvan/challenger-bravo
    tags: [Python, Flask, MongoDb, Heroku]
  item6:
    title: Airbnb Predição de Preços
    subtitle: Análise sobre Airbnb oferecido em Berlin, Alemanha.
    description: ""
    github: https://gist.github.com/iamgilvan/73e2fc5864e4b3dd3c515028d114c488
    tags: [Python, Scikit-Learn, Matplotlib, Seaborn, Numpy, Pandas, Decision Tree Regressor]
  item7:
    title: Airbnb Predição de Demandas
    subtitle: Análise sobre Airbnb oferecido em Berlin, Alemanha.
    description: ""
    github: https://gist.github.com/iamgilvan/06786c9ee39df937cbb04e895b0a5ab3
    tags: [Python, Matplotlib, Seaborn, Numpy, Pandas]
  item9:
    title: Processamento de linguagem natural
    subtitle: Exercício de processamento de linguagem natural.
    description: ""
    github: https://gist.github.com/iamgilvan/2c28d243922980f9c91113da12951388
    img: simple-omnitrix.png
    tags: [Python, Pandas, Scikit-Learn, nltk]
